### ISSUE TITLE
Old way of importing Json

### ISSUE THREAD

**Issue by lorantgulyas** [cph-cachet/carp.core-kotlin#196]
In the Typescript declarations files the current way of importing the `kotlinx.serialisation.json.Json` is:

```
declare module 'carp.core-kotlin-carp.common'
{
    import { Long } from 'kotlin'
    import { kotlinx } from 'kotlinx-serialization-kotlinx-serialization-core-jsLegacy'
    import Json = kotlinx.serialization.json.Json
...
```

However, if I am not mistaken it should be:
```
declare module 'carp.core-kotlin-carp.common'
{
    import { Long } from 'kotlin'
    import { kotlinx } from 'kotlinx-serialization-kotlinx-serialization-json-jsLegacy';
    import Json = kotlinx.serialization.json.Json
...
```

**Comment by Whathecode** [comment]
Which declaration file is this?

From the [alpha 22 release notes](https://github.com/cph-cachet/carp.core-kotlin/releases/tag/v1.0.0-alpha.22):

> - JetBrains changed the artifact name in this release, from kotlinx-serialization-core to kotlinx-serialization-json which you need to update in your dependencies.
> - Correspondingly, the kotlinx.serialization TypeScript declarations have been split into two modules: functions to **get_list_, get_set_, and get_map_ serializers remain in core, but to get access to Json you now need to include the new json module**. ([56eff90](https://github.com/cph-cachet/carp.core-kotlin/commit/56eff903d6b246dbf9ba66586e162547ccec7f42))

The `get_list_` and `get_set_` collection serializer functions have since been renamed to `ListSerializer` and `MapSerializer` which need to be used as constructors [in alpha 23](https://github.com/cph-cachet/carp.core-kotlin/releases/tag/v1.0.0-alpha.23), but, they remain in `kotlinx-serialization-core`.

Therefore, you need to import core in addition to json in case you need the collection initializer functions, as demonstrated in the [studies unit tests](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/typescript-declarations/tests/carp.studies.core.ts):

```
import { kotlinx } from 'kotlinx-serialization-kotlinx-serialization-json-jsLegacy'
import Json = kotlinx.serialization.json.Json
import { kotlinx as kotlinxcore } from 'kotlinx-serialization-kotlinx-serialization-core-jsLegacy'
import ListSerializer = kotlinxcore.serialization.builtins.ListSerializer_swdriu$
```

**Comment by lorantgulyas** [comment]
As in the example, `declare module 'carp.core-kotlin-carp.common'` refers to the [carp.core-kotlin-carp.common/index.d.ts](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/typescript-declarations/%40types/carp.core-kotlin-carp.common/index.d.ts) file.

**Comment by Whathecode** [comment]
Indeed, seemingly the [`common`](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/typescript-declarations/%40types/carp.core-kotlin-carp.common/index.d.ts), [`studies`](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/typescript-declarations/%40types/carp.core-kotlin-carp.studies.core/index.d.ts), and [`protocols`](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/typescript-declarations/%40types/carp.core-kotlin-carp.protocols.core/index.d.ts) import the wrong library. Very weird this was not caught in the tests. 🤔

**Comment by lorantgulyas** [comment]
It's coming from the compiled `carp.core-kotlin-carp.common.js` file
```
Test suite failed to run

    TypeError: Cannot read property 'serialization' of undefined

      10 | import { kotlinx } from 'kotlinx-serialization-kotlinx-serialization-json-jsLegacy';
      11 | import Json = kotlinx.serialization.json.Json;
    > 12 | import { dk as cdk } from 'carp.core-kotlin-carp.common';
         | ^
      13 | import DateTime = cdk.cachet.carp.common.DateTime;
      14 | import UUID = cdk.cachet.carp.common.UUID;
      15 | import EmailAddress = cdk.cachet.carp.common.EmailAddress;

      at node_modules/carp.core-kotlin-carp.common.js:76:88
      at node_modules/carp.core-kotlin-carp.common.js:5:5
      at Object.<anonymous> (node_modules/carp.core-kotlin-carp.common.js:15:2)
      at Object.<anonymous> (src/__tests__/Core.test.ts:12:1)
```

**Comment by Whathecode** [comment]
Fixed!

This was not caught by tests because the tests ran using `mocha --require ts-node/register` which does not seem to care about erroneous imports.

To make sure compilation succeeds now as part of verifying TS declarations, I also run `tsc`. This correctly caught the error, which I now corrected.
