### ISSUE TITLE
Provide the study id in an invitation

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp.core-kotlin#218]
When I get an invitation from CARP as part of the `Participation` in the `ActiveParticipationInvitation` it only provides the `studyDeploymentId`.

I also need the `studyId` in order to use the CARP endpoints which uses the study is -- i.e. the file and document/folder endpoints....

**Comment by Whathecode** [comment]
The `deployment` and `studies` subsystems are decoupled. The `deployment` subsystem, by design, does not know about the `studies` subsystem. We anticipate different implementations of the `study` subsystems should be possible, and they may have different requirements. A deployment could even participate in multiple 'studies' in the current design.

However, it is a common concern to want to send 'application-specific' or custom infrastructure data as part of the invitation. In our current infrastructure, we need to send the `studyId` since we need it for some endpoints which are not included in CARP core. Therefore, [`StudyInvitation` contains a `applicationData` field](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/carp.deployment.core/src/commonMain/kotlin/dk/cachet/carp/deployment/domain/users/StudyInvitation.kt#L25). This field on the current CARP infrastructure is set to `studyId`, thus addressing your primary concern.

That said, it seems there is a common requirement to 'group' deployments. This might be a feature we need to expose within the deployments subsystem, but the dependency should stay unidirectional, from studies to deployments. A dependency in the opposite direction should be avoided at all costs for maintainability/scalability/extendability.
