### ISSUE TITLE
Document `EventBus` implementation requirements for different subsystems.

### ISSUE THREAD

**Issue by Whathecode** [cph-cachet/carp.core-kotlin#230]
We now use an event bus abstraction to communicate across application services. For example, between `StudyService` and `ParticipantService` (https://github.com/cph-cachet/carp.core-kotlin/blob/develop/carp.studies.core/src/commonMain/kotlin/dk/cachet/carp/studies/application/ParticipantServiceHost.kt#L32).

The current implementation of this event bus currently does not dictate whether events may be received out of order. In the example listed above, there is an expectation by the consumer (`ParticipantService`) events from `StudyService` are received in order. Otherwise we may get runtime exceptions on the `checkNotNull` calls.

This particular integration seems easiest to rely on in-order delivery of events. Both services live in the same subsystem as well, so this does not seem like a farfetched requirement (they are expected to be deployed side-by-side, or even on the same machine). However, for other communication of services, such as across subsystems, this might be a big demand on the event bus implementation which reduces scalability.

Can we enforce one implementation or another, or make a correct implementation more likely? At a minimum, this should be documented.

**Comment by Whathecode** [comment]
Kafka apparently uses a _correlation ID_ to determine partitions within which ordering of events is guaranteed. Right now, CARP infrastructure implementations need to know/choose a correct correlation ID (e.g., `studyDeploymentId` might be appropriate for `DeploymentService` events).

Can/should we expose this as part of the `EventBus.publish` so that this does not need to be documented separately and can be implemented in a generic fashion by infrastructure? Maybe `publishOrdered( correlationId )`, or `publish( orderCorrelationId = null )`.

**Comment by ltj** [comment]
I don't think we should use the term "correlation id" here. A correlation id in Kafka context is something  you in the client to map a response from the broker to a request. To ensure ordering across multiple partitions you must provide the same partition _key_ for all outbound messages that must be ordered relative to each other. This key is typically a grouping key, since most often only related messages requires ordering. Most message queue implementations do not have this partitioning scheme and guarantee ordering by using well...a queue. So essentially this should be a "partition key" since this is most generic concept that describes what it is. I still think we should keep it as simple as possible and perhaps simply expose a `partitionKey` property on the events and document to use it if needed.
